[Project]
Name = "Intro"
Version = "0.1.0"
Authors = ["Tim Steenvoorden <tim@cs.ru.nl>"]
# Sourcedir = "1.1-family-tree"
# Sourcedir = "2.1-stepwise-sum"
# Sourcedir = "2.2-stepwise-sum-positive"
# Sourcedir = "2.3-stepwise-sum-back"
# Sourcedir = "3.1-pick-seat"
# Sourcedir = "3.2-pick-free-seat"
Sourcedir = "3.3-flight-reservation"
# Sourcedir = "4.1-meeting-date"
# Sourcedir = "."

[Executable]
Name = "main.exe"
