[Project]
Name = "Intro"
Version = "0.1.0"
Authors = ["Tim Steenvoorden <tim@cs.ru.nl>"]
Sourcedir = "01-family-tree"
# Sourcedir = "02-stepwise-sum"
# Sourcedir = "03-stepwise-sum-positive"
# Sourcedir = "04-stepwise-sum-back"
# Sourcedir = "05-pick-seat"
# Sourcedir = "06-flight-reservation"
# Sourcedir = "07-meeting-date"

[Executable]
Name = "main.exe"
